def FirstTask(a, b):
    print("a + b =", a+b)
    print("a - b =", a-b)
    print("a * b =", a*b)
    print("a / b =", a/b)
    print("a // b =", a//b)
    print("a '%' b =", a%b)
    print("a**b =", a**b)
    print("a < b =", a<b)
    print("a <= b", a<=b)
    print("a > b", a>b)
    print("a >= b", a>=b)
